/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_detai_9;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TrinhBac
 */
public class GUI_program_file extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private static ArrayList<BienLai> danhSach = new ArrayList<>();
    private static int n=-1;
    public static final String file_url ="D:/Java/BTL_DeTai_9/src/btl_detai_9/data.txt";
    
    public GUI_program_file() throws FileNotFoundException {
        initComponents();
        jTextField1.requestFocus();
        danhSach.clear();  
        Scanner sc = new Scanner(new File(file_url));
        if (sc.hasNextLine()) {
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                System.out.println(line);
                String[] a = line.split("/");
//                for(int i=0;i<a.length;i++)
//                    System.out.println(a[i]);
                BienLai b = new BienLai(Integer.parseInt(a[0]), a[1], a[2], a[3], Double.parseDouble(a[4]), Double.parseDouble(a[5]));
                danhSach.add(b);
            } 
            sc.close();
        }
        disPlayTableData();
    }

    public void disPlayTableData() throws FileNotFoundException
    {
        DefaultTableModel model = new DefaultTableModel();
        Vector<String> headerColumn = new Vector<>();
        headerColumn.add("ID");
        headerColumn.add("Ten chu ho");
        headerColumn.add("So nha");
        headerColumn.add("Ma cong to");
        headerColumn.add("Chi so cu");
        headerColumn.add("Chi so moi");
        headerColumn.add("Tien dien");
        model.setColumnIdentifiers(headerColumn);
        
        ArrayList<String> arrRow = new ArrayList<>();
        for (int i = 0; i < danhSach.size(); i++) {
            arrRow.clear();
            arrRow.add(String.valueOf(danhSach.get(i).getID()) );
            arrRow.add(String.valueOf(danhSach.get(i).hoTen) );
            arrRow.add(String.valueOf(danhSach.get(i).soNha) );
            arrRow.add(String.valueOf(danhSach.get(i).maCongTo) );
            arrRow.add(String.valueOf(danhSach.get(i).getChiSoCu()) );
            arrRow.add(String.valueOf(danhSach.get(i).getChiSoMoi()) );
            arrRow.add(String.valueOf(danhSach.get(i).getTienDien()) );
            model.addRow(arrRow.toArray());
        }       
        jTable1.setModel(model);
    }
    
    public void updateDataToFile() throws FileNotFoundException, IOException{
        OutputStream outputStream = new FileOutputStream(new File(file_url));   //true ghi tiếp vào file
        OutputStreamWriter outputStreamWriter = new OutputStreamWriter(outputStream);
        
        for (int i = 0; i < danhSach.size(); i++) {
            outputStreamWriter.write(danhSach.get(i).dataFormatted() + "\n");
        }
        // bắt chương trình chờ ghi dữ liệu xong thì mới kết thúc chương trình.
        outputStreamWriter.flush();
        System.out.println("--> Da ghi du lieu vao file.");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý biên lai");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(500, 200));

        jLabel1.setText("Họ tên chủ hộ :");

        jLabel2.setText("Số nhà :");

        jLabel3.setText("Mã công tơ :");

        jLabel4.setText("Chỉ số cũ :");

        jLabel5.setText("Chỉ số mới :");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Đặt lại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên chủ hộ", "Số nhà", "Mã công tơ", "chỉ số cũ", "Chỉ số mới", "Tiền điện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jButton5.setText("Sắp xếp theo tên");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sắp xếp giảm theo tiền điện");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Biên lai thu tiền điện");

        jLabel7.setText("ID :");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("Auto Increment");

        jButton7.setText("Sắp xếp theo ID");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>                        
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField1.requestFocus();
    }                                        
    
//    add function
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //loi id
        int max=0;
        for(int i=0;i<danhSach.size();i++){
            if(danhSach.get(i).getID()>max)
                max=danhSach.get(i).getID();
        }
        
        int id = max+1;
        String hoTen = jTextField1.getText();
        String soNha = jTextField2.getText();
        String maCongTo = jTextField4.getText();
        double chiSoCu = -1, chiSoMoi = -1;
        try{
            chiSoCu = Double.parseDouble(jTextField3.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Chi so cu phai la so !");
            jTextField3.setText(null);
            jTextField3.requestFocus();
        }
        try{
            chiSoMoi = Double.parseDouble(jTextField5.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Chi so moi phai la so !");
            jTextField5.setText(null);
            jTextField5.requestFocus();
        }
        if(chiSoCu!=-1 && chiSoMoi!=-1){
            BienLai b = new BienLai(id, hoTen, soNha, maCongTo, chiSoCu, chiSoMoi);
            danhSach.add(b);
            try {
                updateDataToFile();
                disPlayTableData();
                JOptionPane.showMessageDialog(this, "Them thanh cong !");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Collections.sort(danhSach, new Comparator<BienLai>(){
            public int compare(BienLai a, BienLai b){
                return (a.hoTen.compareTo(b.hoTen));
            }
        });
        System.out.println("--> Da sap xep tang theo ten.");
        try {
            updateDataToFile();
            disPlayTableData();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Collections.sort(danhSach, new Comparator<BienLai>(){
            public int compare(BienLai a, BienLai b){
                if(a.getTienDien()<b.getTienDien())
                    return 1;
                else
                    return -1;
            }
        });
        System.out.println("--> Da sap xep giam theo tiem dien.");
        try {
            updateDataToFile();
            disPlayTableData();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Collections.sort(danhSach, new Comparator<BienLai>(){
            public int compare(BienLai a, BienLai b){
                if(a.getID()<b.getID())
                    return -1;
                else
                    return 1;
            }
        });
        System.out.println("--> Da sap xep tang theo ID.");
        try {
            updateDataToFile();
            disPlayTableData();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex>-1){
            jTextField1.setText(jTable1.getModel().getValueAt(rowIndex, 1).toString());
            jTextField2.setText(jTable1.getModel().getValueAt(rowIndex, 2).toString());
            jTextField4.setText(jTable1.getModel().getValueAt(rowIndex, 3).toString());
            jTextField3.setText(jTable1.getModel().getValueAt(rowIndex, 4).toString());
            jTextField5.setText(jTable1.getModel().getValueAt(rowIndex, 5).toString());
            jTextField6.setText(jTable1.getModel().getValueAt(rowIndex, 0).toString());
            
        }
    }                                    
    
//    public boolean checkID(){
//        //
//    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            // TODO add your handling code here:
            int id = Integer.parseInt(jTextField6.getText()) ;
            Iterator<BienLai> it = danhSach.iterator();
            while(it.hasNext()){
                BienLai b = it.next();
                if(b.getID()==id)
                    it.remove();
            }
            String mgs = String.format("Da xoa bien lai co id la %d", id);
            System.out.println(mgs);
            JOptionPane.showMessageDialog(this, mgs);
            updateDataToFile();
            disPlayTableData();
        } catch (IOException ex) {
            Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

//    update function
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextField6.getText());
        String hoTen = jTextField1.getText();
        String soNha = jTextField2.getText();
        String maCongTo = jTextField4.getText();
        double chiSoCu = -1, chiSoMoi = -1;
        try{
            chiSoCu = Double.parseDouble(jTextField3.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Chi so cu phai la so !");
            jTextField3.setText(null);
            jTextField3.requestFocus();
        }
        try{
            chiSoMoi = Double.parseDouble(jTextField5.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Chi so moi phai la so !");
            jTextField5.setText(null);
            jTextField5.requestFocus();
        }
        if(chiSoCu!=-1 && chiSoMoi!=-1){
            BienLai b = new BienLai(id, hoTen, soNha, maCongTo, chiSoCu, chiSoMoi);
            for (int i = 0; i < danhSach.size(); i++) {
                if(danhSach.get(i).getID()==id){
                    danhSach.set(i, b);
                    JOptionPane.showMessageDialog(this, "Sua thanh cong !"); 
                }
            }
            try {
                updateDataToFile();
                disPlayTableData();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_program_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_program_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_program_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_program_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_program_file().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GUI_program_file.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}
